/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;


import aktivne_niti.NitActiveUsers;
import aktivne_niti.NitLiveChat;
import forme.model.ModelTabeleAktivni;
import forme.model.ModelTabelePoruke;
import java.util.List;
import java.awt.Point;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import komunikacija.Komunikacija;
import model.Poruka;
import model.User;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Acer
 */
public class ClientWorkingForm extends javax.swing.JFrame {
    
    //GETTERS AND SETTERS ZA NIT  KLIJENTI STIZU...........

    public User getUlogovaniUser() {
        return ulogovaniUser;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JButton getjButtonPosalji() {
        return jButtonPosalji;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTable getjTableAktivni() {
        return jTableAktivni;
    }


    public JTextArea getjTextAreaPoruka() {
        return jTextAreaPoruka;
    }

    public JTable getjTableAnotherMessages() {
        return jTableAnotherMessages;
    }

    public void setjTableAnotherMessages(JTable jTableAnotherMessages) {
        this.jTableAnotherMessages = jTableAnotherMessages;
    }

    public JTable getjTableLastThreeMess() {
        return jTableLastThreeMess;
    }

    public void setjTableLastThreeMess(JTable jTableLastThreeMess) {
        this.jTableLastThreeMess = jTableLastThreeMess;
    }



   
    
    
  //GETTERS AND SETTERS ...............................
User ulogovaniUser=null;
    /**
     * Creates new form ClientWorkingForm
     */

   




    public ClientWorkingForm(User u) {
        initComponents();
        ulogovaniUser = u;
        //System.out.println("CLIENT WORKING FORM: "+ulogovaniUser);
        //************************************************************
        NitActiveUsers nau = new NitActiveUsers();
        nau.setCwf(this);
        nau.start();
        
        
   //*****************************************************************

    
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPoruka = new javax.swing.JTextArea();
        jButtonPosalji = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAktivni = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLastThreeMess = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableAnotherMessages = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMessagesFromUser = new javax.swing.JTable();
        jButtonViewChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SEND MESSAGE");

        jTextAreaPoruka.setColumns(20);
        jTextAreaPoruka.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPoruka);

        jButtonPosalji.setText("SEND TO ALL");
        jButtonPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosaljiActionPerformed(evt);
            }
        });

        jTableAktivni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAktivni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAktivniMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAktivni);

        jLabel2.setText("ACTIVE USERS");

        jButton1.setText("SEND TO ONE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("LAST 3 MESSAGES RECEIVED");

        jLabel4.setText("ANOTHER MESSAGES");

        jTableLastThreeMess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableLastThreeMess);

        jTableAnotherMessages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableAnotherMessages);

        jLabel5.setText("MESSAGES FROM SELLECTED USER");

        jTableMessagesFromUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMessagesFromUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMessagesFromUserMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableMessagesFromUser);

        jButtonViewChat.setText("VIEW CHAT");
        jButtonViewChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(90, 90, 90)
                        .addComponent(jButtonViewChat)
                        .addGap(159, 159, 159)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonViewChat))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPosalji)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosaljiActionPerformed
       
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.POSALJI_SVIM_ULOGOVANIM);
        
        Poruka p = new Poruka();
        String txt = jTextAreaPoruka.getText();
        if(txt.length()>200){
            JOptionPane.showMessageDialog(null, "Poruka je duza od 200 karaktera.");
            
        }else{
            
            p.setText(txt);
            p.setSender(ulogovaniUser);
            p.setReciever(null);
            p.setDatumVreme(new Date());
            
            
        }
        
         kz.setParam(p);
        
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        //*****************
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        String odg = (String) so.getOdgovor();
        
        JOptionPane.showMessageDialog(null, "Uspesno poslata poruka svim ulogovanim userima!");
       
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonPosaljiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        String txtPoruke = jTextAreaPoruka.getText();
        
        int index = jTableAktivni.getSelectedRow();
        
          if(index==-1){
              JOptionPane.showMessageDialog(null, "Greska pri selektovanju primaoca.");
            return;
        }
        
        if(jTextAreaPoruka.getText().length()>200){
            JOptionPane.showMessageDialog(null, "Poruka je predugacka.");
        }else{
            
            ModelTabeleAktivni mta = (ModelTabeleAktivni) jTableAktivni.getModel();
            User u = mta.getUsers().get(index);
            
            //*********************
            Poruka p = new Poruka();
            p.setDatumVreme(new Date());
            p.setSender(ulogovaniUser);
            p.setReciever(u);
            p.setText(txtPoruke);
            
            KlijentskiZahtev kz = new KlijentskiZahtev();
            kz.setOperacija(Operacije.POSALJI_JEDNOM);
            kz.setParam(p);
            
            Komunikacija.getInstance().posaljiZahtev(kz);
            //******
            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            String odg = (String) so.getOdgovor();
            JOptionPane.showMessageDialog(null, odg);
            
            
        }
        
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableAktivniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAktivniMouseClicked
      
        
        JTable tabela = (JTable) evt.getSource();
        Point point = evt.getPoint();
        
        
        int idex = tabela.rowAtPoint(point);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.VRATI_PORUKE_ISTOG_SENDERA);
        
        ModelTabeleAktivni mta = (ModelTabeleAktivni) jTableAktivni.getModel();
        ArrayList<User> users = mta.getUsers();
        User SelectedUser = users.get(idex);
        
        
        kz.setParam(SelectedUser);
        
        Komunikacija.getInstance().posaljiZahtev(kz);
        //***************
        
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        ArrayList<Poruka> poruke = (ArrayList<Poruka>) so.getOdgovor();
        
        ModelTabelePoruke mtpZahtev = new ModelTabelePoruke(poruke);
        jTableMessagesFromUser.setModel(mtpZahtev);
        
    }//GEN-LAST:event_jTableAktivniMouseClicked

    private void jTableMessagesFromUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMessagesFromUserMouseClicked
      
        JTable tabela = (JTable) evt.getSource();
        Point point = evt.getPoint();
        
        int index = tabela.rowAtPoint(point);
        
        
        ModelTabelePoruke mtp = (ModelTabelePoruke) jTableMessagesFromUser.getModel();
        Poruka p = mtp.getPoruke().get(index);
        String text = p.getText();
        JOptionPane.showMessageDialog(null, text);
        
        
        
    }//GEN-LAST:event_jTableMessagesFromUserMouseClicked

    private void jButtonViewChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewChatActionPerformed
        NitLiveChat nlc = new NitLiveChat();
        nlc.setCwf(this);
        nlc.start();
   
        
    }//GEN-LAST:event_jButtonViewChatActionPerformed

  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPosalji;
    private javax.swing.JButton jButtonViewChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableAktivni;
    private javax.swing.JTable jTableAnotherMessages;
    private javax.swing.JTable jTableLastThreeMess;
    private javax.swing.JTable jTableMessagesFromUser;
    private javax.swing.JTextArea jTextAreaPoruka;
    // End of variables declaration//GEN-END:variables


 

    }
  

